### PR TITLE
Added date&time based expiration, and redirect to specific dashboard

### PR DESCRIPTION
**Pull request by marcbodea**
Hi, thanks a lot for the project. I made some changes for my personal use and thought they might be useful for others as well:

1. added date&time based expiration to keys
2. defaulted the user selector to "guest"
3. added a redirect to specific dashboard in the login.html page, which is parsed from the URL – since you cannot add tabs to the overview dashboard without it 'breaking', i suggest creating a "guest" dashboard, which the user will be redirected to automatically, and enabling kiosk on there
4. defaulted dashboard text field to dashboard-guest

I couldn't for the life of me get ha-time-input and ha-checkbox input fields to work, so edits on that would be appreciated.
I also wanted to suggest creating 2 separate repos for the dashboard and integration side of things, so that updates can be pushed without requiring the user to install, delete repo, reinstall

Mersi inca o data :)

### CODE REVIEW

**Comment by kcsoft** [comment]
Thank you for contributing to this, hopefully we can add more improvements together.

1. time/date exp sounds like a good idea
2. I would avoid hardcoding anything. Instead maybe we can ready the default user from the config or we can sort them alpha and you can give your guest user some name like "!guest" to boost his position
3. I don't think we need this. You can add dashboards to lovelace that are visible to specific user and if the user only has one visible dashboard, that will be his default one. Also if you set a default dash, you will need to do this for every user since you might want to redirect them to specific dash.
image

4. Again, I would avoid any hardcoded settings but as mentioned on 3., I don't think we need to specify the dashboard/redirect.

On splitting the repo into 2 separate, yes, that might be a good idea, easier for the users to install and update.

**Comment by marcbodea** [comment]
Hi, thanks for the reply.

2. Yeah, you're right. I think the optimal solution would be a settings pane that lets users set these defaults, second best would be what you mentioned, 1st alphabetical option
3. I have 2 worries here:
- It seems that you can set visibility of tabs on dashboards, but not the dashboards themselves – this means the dashboards still show up in the menu but redirect to a blank page on click.
- It seems you cannot set the visbility of the default 'overview' dashboard, so for those who have that one still enabled, when logging in as guest user, that is the one that opens by default. It is a half-issue since the only entities that show up are the ones that the guest has access to, but they wouldn't see the dashboard created for them straight away, and can access other things I wouldn't want them to access like Logbook, History, Media, which can be hidden on a device basis, but not user basis.

In light of these, I think from a security and ease of use point of view, setting a redirect is a good way to get some extra security without the user needing to dive into YAML configurations. It also gives ones that can't or won't edit the auth file (correct me if I'm wrong but you need to SSH in to access it, not even the file editor add-on can see it) a bit more security by pushing guests straight to kiosk.

Do you think it's possible to implement a small settings pane just on the frontend side of things? Not sure how storing those settings would work

**Comment by kcsoft** [comment]
for the date picker, added  [here](https://github.com/kcsoft/virtual-keys/pull/10), please see if this meets your needs

**Comment by marcbodea** [comment]
> for the date picker, added [here](https://github.com/kcsoft/virtual-keys/pull/10), please see if this meets your needs

yup, looks good. Thanks!

**Pull request closed without merging**
